version: "3.8"

services:
  otel-lgtm:
    image: grafana/otel-lgtm:latest
    container_name: otel-lgtm
    ports:
      - "3000:3000"     # Grafana
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
    tty: true
    stdin_open: true
    restart: unless-stopped

