receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      disk:
      filesystem:
      network:
      load:
  prometheus:
      config:
        scrape_configs:
          - job_name: 'http-status-checker'
            scrape_interval: 15s
            static_configs:
              - targets: ['http-status-checker:1738']
processors:
  batch:

exporters:
  otlp:
    endpoint: http://otel-lgtm:4317
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [hostmetrics, prometheus]
      processors: [batch]
      exporters: [otlp]
